[package]
name = "tor_launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
rfd = "0.14"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
windivert = "0.6"
